#!/usr/bin/env bash
function addToPATH {
  case ":$PATH:" in
    *":$1:"*) :;; # already there
    *) PATH="$1:$PATH";; # or PATH="$PATH:$1"
  esac
}

# Path to your oh-my-zsh installation.
# https://ourcodeworld.com/articles/read/1506/how-to-remove-the-zsh-message-in-the-terminal-of-macos-bigsur-ignore-insecure-directories-and-continue-or-abort-compinit
export ZSH_DISABLE_COMPFIX=true
export ZSH=$HOME/.oh-my-zsh
export NPM_CONFIG_PREFIX=$HOME/.npm-global
# export N_PREFIX=$HOME/.n
addToPATH $HOME/.dotfiles/programs
addToPATH $NPM_CONFIG_PREFIX/bin
addToPATH $HOME/n/bin
addToPATH $HOME/.pyenv/bin

PATH=$(echo "$PATH" | sed -e 's/\/mnt\/c\/Program Files\/nodejs://')
PATH=$(echo "$PATH" | sed -e 's/\/mnt\/c\/Users\/jburkholder\/AppData\/Roaming\/npm://')
PATH=$(echo "$PATH" | sed -e 's/\/mnt\/c\/Program Files (x86)\/Yarn\/bin://')

export PATH=$PATH


