#!/usr/bin/env bash

if [[ $OSTYPE == 'darwin'* ]]; then
session=$(find  $(wslpath $HOME -mindepth 1 -maxdepth 2 -type d | fzf)
else
session=$(find  $(wslpath "$(wslvar USERPROFILE)") -mindepth 1 -maxdepth 2 -type d | fzf)
fi
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null ; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
